[theme]
primaryColor = "#2E7D32"
backgroundColor = "#FAFAF9"
secondaryBackgroundColor = "#EDF1EE"
textColor = "#0F172A"
font = "sans serif"



[client]
# Hides the Streamlit developer options menu in the top right 
# to make the app feel like a proprietary commercial product.
toolbarMode = "viewer"

# Since you are building a multi-grade system with separate pages, 
# you can leave this true to keep the native sidebar navigation, 
# or set to false if you plan to build custom navigation buttons.
showSidebarNavigation = true